import { z } from "zod";

export const demographicFormSchema = z.object({
  firstName: z.string().min(1, { message: "First Name is required" }),
  middleName: z.string().min(1, { message: "Middle Name is required" }),
  lastName: z.string().min(1, { message: "Last Name is required" }),
  ssn: z.string().length(9, { message: "SSN is required" }),
  dateOfBirth: z.coerce.date<Date>({ message: "Date of Birth is required" }),
  gender: z.enum(["male", "female"]),
  tomis: z
    .string()
    .regex(/^\d+$/, { message: "TOMIS must contain only digits" })
    .length(8, { message: "TOMIS must be 8 digits" }),
  // email: z.email({ message: "Please enter a valid email address" }),
  // lastKnownAddress: z.string().min(1, { message: "Address is required" }),
  // cleanTime: z.string().min(1, { message: "This field is required" }),
  // drugOfChoice: z.string().min(1, { message: "This field is required" }),
  // priorRecoveryExperience: z
  //   .string()
  //   .min(1, { message: "This field is required" }),
  // surgeries: z.string().min(1, { message: "This field is required" }),
  // allergies: z.string().min(1, { message: "This field is required" }),
  // medications: z.string().min(1, { message: "This field is required" }),
  // insurance: z.string().min(1, { message: "This field is required" }),
  // receiveBenefits: z.enum(["Yes", "No"]),
  // benefitsDesc: z.string(),
  // isDisabled: z.enum(["Yes", "No"]),
  // disabilityDesc: z.string(),
  // receivesDisability: z.enum(["Yes", "No"]),
  // disabilitiesReceived: z.array(
  //   z.object({
  //     reason: z.string(),
  //     amount: z.string(),
  //   }),
  // ),
  // receivesFoodStamps: z.enum(["Yes", "No"]),
  // hasMentalHealthRecs: z.enum(["Yes", "No"]),
  // mentalHealthRecs: z.string(),
  // participatingInTreatment: z.enum(["Yes", "No"]),
  // typeOfTreatment: z.string(),
  // howOften: z.string(),
  // locationOfTreatment: z.string(),
  // maritalStatus: z.enum(["Single", "Married", "Divorced"]),
  // hasChildren: z.enum(["Yes", "No"]),
  // numberOfChildren: z.string(),
  // isPregnant: z.enum(["Yes", "No"]),
  // currentEmployment: z.string().min(1, { message: "This field is required" }),
  // employmentContactInfo: z
  //   .string()
  //   .min(1, { message: "This field is required" }),
  // employmentStartDate: z.string().min(1, { message: "Start date is required" }),
  // employmentEndDate: z.string().min(1, { message: "End date is required" }),
  // servedInMilitary: z.enum(["Yes", "No"]),
  // militaryBranch: z.enum([
  //   "Army",
  //   "Navy",
  //   "Air Force",
  //   "Marines",
  //   "Coast Guard",
  // ]),
  // militaryStartDate: z.string(),
  // militaryEndDate: z.string(),
  // militaryDischarge: z.string(),
  // hasHighSchoolDiploma: z.enum(["Yes", "No"]),
  // hasGED: z.enum(["Yes", "No"]),
  // hasCollegeDegree: z.enum(["Yes", "No"]),
  // hasDriversLicense: z.enum(["Yes", "No"]),
  // driversLicenseNumber: z
  //   .string()
  //   .regex(/^[A-Z0-9]+$/i, {
  //     message: "Driver's license must contain only letters and numbers",
  //   })
  //   .min(1),
  // dlIssueDate: z.string(),
  // dlExpDate: z.string(),
  // convictedOfDUI: z.enum(["Yes", "No"]),
  // duiYear: z.string(),
  // convictedOfSexOffense: z.enum(["Yes", "No"]),
  // registeredSexOffender: z.enum(["Yes", "No"]),
  // sexOffenseNature: z.string(),
  // convictedOfFelony: z.enum(["Yes", "No"]),
  // felonyCharges: z.string(),
  // onProbationOrParole: z.enum(["Yes", "No"]),
  // officerContactInfo: z.string(),
  // inRecoveryCourt: z.enum(["Yes", "No"]),
  // caseManagerContactInfo: z.string(),
  // ongoingLegalIssues: z.string().min(1, { message: "This field is required" }),
});

export type DemographicFormValues = z.infer<typeof demographicFormSchema>;

export const demographicFormDefaultValues: DemographicFormValues = {
  firstName: "",
  middleName: "",
  lastName: "",
  ssn: "",
  dateOfBirth: new Date(),
  gender: "female",
  tomis: "",
  // email: "",
  // lastKnownAddress: "",
  // cleanTime: "",
  // drugOfChoice: "",
  // priorRecoveryExperience: "",
  // surgeries: "",
  // allergies: "",
  // medications: "",
  // insurance: "",
  // receiveBenefits: "No",
  // benefitsDesc: "",
  // isDisabled: "No",
  // disabilityDesc: "",
  // receivesDisability: "No",
  // disabilitiesReceived: [{ reason: "", amount: "" }],
  // receivesFoodStamps: "No",
  // hasMentalHealthRecs: "No",
  // mentalHealthRecs: "",
  // participatingInTreatment: "No",
  // typeOfTreatment: "",
  // howOften: "",
  // locationOfTreatment: "",
  // maritalStatus: "Single",
  // hasChildren: "No",
  // numberOfChildren: "",
  // isPregnant: "No",
  // currentEmployment: "",
  // employmentContactInfo: "",
  // employmentStartDate: "",
  // employmentEndDate: "",
  // servedInMilitary: "No",
  // militaryBranch: "Army",
  // militaryStartDate: "",
  // militaryEndDate: "",
  // militaryDischarge: "",
  // hasHighSchoolDiploma: "No",
  // hasGED: "No",
  // hasCollegeDegree: "No",
  // hasDriversLicense: "No",
  // driversLicenseNumber: "",
  // dlIssueDate: "",
  // dlExpDate: "",
  // convictedOfDUI: "No",
  // duiYear: "",
  // convictedOfSexOffense: "No",
  // registeredSexOffender: "No",
  // sexOffenseNature: "",
  // convictedOfFelony: "No",
  // felonyCharges: "",
  // onProbationOrParole: "No",
  // officerContactInfo: "",
  // inRecoveryCourt: "No",
  // caseManagerContactInfo: "",
  // ongoingLegalIssues: "",
};
