import { DefaultValues } from "react-hook-form";
import { z } from "zod";

import {
  optionalText,
  requiredEmail,
  requiredPhone,
  requiredText,
  yesNo,
} from "@/utils/form/validations";

export const demographicFormSchema = z.object({
  firstName: requiredText("First name is required"),
  middleName: optionalText,
  lastName: requiredText("Last name is required"),
  socialSecurityNumber: requiredText("Social security number is required"),
  ethnicity: z.enum(
    [
      "White",
      "Black or African American",
      "American Indian or Alaska Native",
      "Asian",
      "Native Hawaiian or Other Pacific Islander",
      "Other",
    ],
    "Ethnicity is required",
  ),
  dateOfBirth: requiredText("Date of birth is required"),
  phoneNumber: requiredPhone("Phone number is required"),
  tomis: requiredText("TOMIS is required"),
  email: requiredEmail("Email is required"),
  lastKnownAddress: optionalText,
  cleanTime: optionalText,
  drugOfChoice: optionalText,
  priorRecoveryExperience: optionalText,
  surgeries: optionalText,
  allergies: optionalText,
  medications: optionalText,
  insurance: optionalText,
  receiveBenefits: yesNo,
  benefitsDesc: optionalText,
  isDisabled: yesNo,
  disabilityDesc: optionalText,
  receivesDisability: yesNo,
  receivesDisabilityReason: optionalText,
  receivedDisabilityAmount: optionalText,
  receivesFoodStamps: yesNo,
  hasMentalHealthRecs: yesNo,
  mentalHealthRecs: optionalText,
  participatingInTreatment: yesNo,
  typeOfTreatment: optionalText,
  howOften: optionalText,
  locationOfTreatment: optionalText,
  maritalStatus: z.enum(["Single", "Married", "Divorced"]).optional(),
  hasChildren: yesNo,
  numberOfChildren: optionalText,
  isPregnant: yesNo,
  currentEmployment: optionalText,
  employmentContactInfo: optionalText,
  employmentStartDate: optionalText,
  employmentEndDate: optionalText,
  servedInMilitary: yesNo,
  militaryBranch: z
    .enum(["Army", "Navy", "Air Force", "Marines", "Coast Guard"])
    .optional(),
  militaryStartDate: optionalText,
  militaryEndDate: optionalText,
  militaryDischarge: optionalText,
  hasHighSchoolDiploma: yesNo,
  hasGED: yesNo,
  hasCollegeDegree: yesNo,
  hasDriversLicense: yesNo,
  driversLicenseNumber: optionalText,
  dlIssueDate: optionalText,
  dlExpDate: optionalText,
  convictedOfDUI: yesNo,
  duiYear: optionalText,
  convictedOfSexOffense: yesNo,
  registeredSexOffender: yesNo,
  sexOffenseNature: optionalText,
  convictedOfFelony: yesNo,
  felonyCharges: optionalText,
  onProbationOrParole: yesNo,
  officerContactInfo: optionalText,
  inRecoveryCourt: yesNo,
  caseManagerContactInfo: optionalText,
  ongoingLegalIssues: optionalText,
});

export type DemographicFormValues = z.infer<typeof demographicFormSchema>;

export const demographicFormDefaultValues: DefaultValues<DemographicFormValues> =
  {
    firstName: "",
    middleName: "",
    lastName: "",
    socialSecurityNumber: "",
    ethnicity: undefined,
    dateOfBirth: "",
    phoneNumber: "",
    tomis: "",
    email: "",
    lastKnownAddress: "",
    cleanTime: "",
    drugOfChoice: "",
    priorRecoveryExperience: "",
    surgeries: "",
    allergies: "",
    medications: "",
    insurance: "",
    receiveBenefits: undefined,
    benefitsDesc: "",
    isDisabled: undefined,
    disabilityDesc: "",
    receivesDisability: undefined,
    receivesDisabilityReason: "",
    receivedDisabilityAmount: "",
    receivesFoodStamps: undefined,
    hasMentalHealthRecs: undefined,
    mentalHealthRecs: "",
    participatingInTreatment: undefined,
    typeOfTreatment: "",
    howOften: "",
    locationOfTreatment: "",
    maritalStatus: undefined,
    hasChildren: undefined,
    numberOfChildren: "",
    isPregnant: undefined,
    currentEmployment: "",
    employmentContactInfo: "",
    employmentStartDate: "",
    employmentEndDate: "",
    servedInMilitary: undefined,
    militaryBranch: undefined,
    militaryStartDate: "",
    militaryEndDate: "",
    militaryDischarge: "",
    hasHighSchoolDiploma: undefined,
    hasGED: undefined,
    hasCollegeDegree: undefined,
    hasDriversLicense: undefined,
    driversLicenseNumber: "",
    dlIssueDate: "",
    dlExpDate: "",
    convictedOfDUI: undefined,
    duiYear: "",
    convictedOfSexOffense: undefined,
    registeredSexOffender: undefined,
    sexOffenseNature: "",
    convictedOfFelony: undefined,
    felonyCharges: "",
    onProbationOrParole: undefined,
    officerContactInfo: "",
    inRecoveryCourt: undefined,
    caseManagerContactInfo: "",
    ongoingLegalIssues: "",
  };
