import { z } from "zod";

export const medicalHistoryFormSchema = z.object({
  surgeries: z.string().min(1, { message: "This field is required" }),
  allergies: z.string().min(1, { message: "This field is required" }),
  medications: z.string().min(1, { message: "This field is required" }),
  insurance: z.string().min(1, { message: "This field is required" }),
  receiveBenefits: z.enum(["Yes", "No"]),
  benefitsDesc: z.string(),
  isDisabled: z.enum(["Yes", "No"]),
  disabilityDesc: z.string(),
  receivesDisability: z.enum(["Yes", "No"]),
  disabilitiesReceived: z.array(
    z.object({
      reason: z.string(),
      amount: z.string(),
    }),
  ),
  receivesFoodStamps: z.enum(["Yes", "No"]),
  hasMentalHealthRecs: z.enum(["Yes", "No"]),
  mentalHealthRecs: z.string(),
  participatingInTreatment: z.enum(["Yes", "No"]),
  typeOfTreatment: z.string(),
  howOften: z.string(),
  locationOfTreatment: z.string(),
  maritalStatus: z.enum(["Single", "Married", "Divorced"]),
  hasChildren: z.enum(["Yes", "No"]),
  numberOfChildren: z.string(),
  isPregnant: z.enum(["Yes", "No"]),
  currentEmployment: z.string().min(1, { message: "This field is required" }),
  employmentContactInfo: z
    .string()
    .min(1, { message: "This field is required" }),
  employmentStartDate: z.coerce.date<Date>({
    message: "Start date is required",
  }),
  employmentEndDate: z.coerce.date<Date>({ message: "End date is required" }),
  servedInMilitary: z.enum(["Yes", "No"]),
  militaryBranch: z.enum([
    "Army",
    "Navy",
    "Air Force",
    "Marines",
    "Coast Guard",
  ]),
  militaryStartDate: z.coerce.date<Date>({ message: "Start date is required" }),
  militaryEndDate: z.coerce.date<Date>({ message: "End date is required" }),
  militaryDischarge: z.string(),
  hasHighSchoolDiploma: z.enum(["Yes", "No"]),
  hasGED: z.enum(["Yes", "No"]),
  hasCollegeDegree: z.enum(["Yes", "No"]),
  hasDriversLicense: z.enum(["Yes", "No"]),
  driversLicenseNumber: z
    .string()
    .regex(/^[A-Z0-9]+$/i, {
      message: "Driver's license must contain only letters and numbers",
    })
    .min(1),
  dlIssueDate: z.coerce.date<Date>({ message: "Issue date is required" }),
  dlExpDate: z.coerce.date<Date>({ message: "Expiration date is required" }),
  convictedOfDUI: z.enum(["Yes", "No"]),
  duiYear: z.string(),
  convictedOfSexOffense: z.enum(["Yes", "No"]),
  registeredSexOffender: z.enum(["Yes", "No"]),
  sexOffenseNature: z.string(),
  convictedOfFelony: z.enum(["Yes", "No"]),
  felonyCharges: z.string(),
  onProbationOrParole: z.enum(["Yes", "No"]),
  officerContactInfo: z.string(),
  inRecoveryCourt: z.enum(["Yes", "No"]),
  caseManagerContactInfo: z.string(),
  ongoingLegalIssues: z.string().min(1, { message: "This field is required" }),
});

type MedicalHistoryFormValues = z.infer<typeof medicalHistoryFormSchema>;

export const medicalHistoryFormDefaultValues: MedicalHistoryFormValues = {
  surgeries: "",
  allergies: "",
  medications: "",
  insurance: "",
  receiveBenefits: "No",
  benefitsDesc: "",
  isDisabled: "No",
  disabilityDesc: "",
  receivesDisability: "No",
  disabilitiesReceived: [{ reason: "", amount: "" }],
  receivesFoodStamps: "No",
  hasMentalHealthRecs: "No",
  mentalHealthRecs: "",
  participatingInTreatment: "No",
  typeOfTreatment: "",
  howOften: "",
  locationOfTreatment: "",
  maritalStatus: "Single",
  hasChildren: "No",
  numberOfChildren: "",
  isPregnant: "No",
  currentEmployment: "",
  employmentContactInfo: "",
  employmentStartDate: new Date(),
  employmentEndDate: new Date(),
  servedInMilitary: "No",
  militaryBranch: "Army",
  militaryStartDate: new Date(),
  militaryEndDate: new Date(),
  militaryDischarge: "",
  hasHighSchoolDiploma: "No",
  hasGED: "No",
  hasCollegeDegree: "No",
  hasDriversLicense: "No",
  driversLicenseNumber: "12345",
  dlIssueDate: new Date(),
  dlExpDate: new Date(),
  convictedOfDUI: "No",
  duiYear: "",
  convictedOfSexOffense: "No",
  registeredSexOffender: "No",
  sexOffenseNature: "",
  convictedOfFelony: "No",
  felonyCharges: "",
  onProbationOrParole: "No",
  officerContactInfo: "",
  inRecoveryCourt: "No",
  caseManagerContactInfo: "",
  ongoingLegalIssues: "",
};
